<a href="https://colab.research.google.com/github/Vibhutideshmukh/python../blob/main/Numpy2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np # import the numpy library and alias it as 'np'

random_3D_cohort = np.array(np.random.randint(10,45,(2,4,6)))
print(f"The defined array is \n{random_3D_cohort}")
print(f" \n The shape of the array is {random_3D_cohort.shape}")

The defined array is 
[[[29 41 25 38 42 36]
  [44 11 15 28 39 28]
  [32 36 29 23 14 28]
  [27 26 39 17 33 22]]

 [[42 31 39 19 43 18]
  [22 42 29 38 22 31]
  [27 10 19 16 39 16]
  [44 34 12 33 12 28]]]
 
 The shape of the array is (2, 4, 6)


In [9]:

a = np.random.randint(2,6,(2,3,3))
print(a)
print(a.shape)

[[[2 2 3]
  [3 4 4]
  [2 4 3]]

 [[2 2 3]
  [5 4 3]
  [4 4 2]]]
(2, 3, 3)


In [ ]:
new_shape = (2,3,6)
new_shape = (2,3,6)
resized_random_3D_cohort = np.resize(random_3D_cohort,new_shape)
print(f"This resized array is \n{resized_random_3D_cohort}")
print(f" \n The shape of the array is")

This resized array is 
[[[29 41 25 38 42 36]
  [44 11 15 28 39 28]
  [32 36 29 23 14 28]]

 [[27 26 39 17 33 22]
  [42 31 39 19 43 18]
  [22 42 29 38 22 31]]]
 
 The shape of the array is


In [ ]:
new_shape = (2,3,6)
resized_random_3D_cohort = np.resize(random_3D_cohort,new_shape)
print(f"This resized array is \n{resized_random_3D_cohort}")
print(f" \n The shape of the array is {resized_random_3D_cohort.shape}")


This resized array is 
[[[29 41 25 38 42 36]
  [44 11 15 28 39 28]
  [32 36 29 23 14 28]]

 [[27 26 39 17 33 22]
  [42 31 39 19 43 18]
  [22 42 29 38 22 31]]]
 
 The shape of the array is (2, 3, 6)


In [ ]:
import numpy as np
random_3D_cohort = np.array(np.random.randint(10,45,(2,4,6)))
print(f"The defined array is \n{random_3D_cohort}")
print(f" \n The shape of the array is {random_3D_cohort.shape}")


The defined array is 
[[[12 41 22 41 43 12]
  [16 42 33 15 13 29]
  [25 28 23 21 17 28]
  [29 22 24 10 18 28]]

 [[23 36 14 38 34 26]
  [40 31 40 22 35 14]
  [26 33 12 17 16 44]
  [37 17 41 42 13 36]]]
 
 The shape of the array is (2, 4, 6)


In [10]:
import numpy as np
a = np.random.randint(10,20,(2,3,4))   #Axis 0-2 ; Axis 1-3 ; Axis 2-4
print(a)
print(a.shape)

[[[18 17 17 15]
  [19 10 12 12]
  [11 16 13 11]]

 [[19 12 16 11]
  [14 17 13 19]
  [16 19 19 12]]]
(2, 3, 4)


In [ ]:
#Insert along axis = 2
np.insert(a,0,200,axis=2)

array([[[200,  16,  18,  14,  15],
        [200,  13,  11,  10,  17],
        [200,  19,  10,  11,  12]],

       [[200,  18,  14,  15,  12],
        [200,  12,  16,  13,  19],
        [200,  19,  12,  14,  15]]])

In [17]:

#Insert along axis = 0
np.insert(a,1,100,axis=0)

array([[[  5,   5,   3],
        [  3,   2,   3],
        [  4,   4,   3]],

       [[100, 100, 100],
        [100, 100, 100],
        [100, 100, 100]],

       [[  5,   4,   3],
        [  2,   5,   3],
        [  5,   5,   2]]])

In [12]:
print(a)
print(a.shape)

[[[18 17 17 15]
  [19 10 12 12]
  [11 16 13 11]]

 [[19 12 16 11]
  [14 17 13 19]
  [16 19 19 12]]]
(2, 3, 4)


In [13]:
b = np.random.randint(2,6,(2,1,3))
print(b)

[[[2 4 2]]

 [[5 3 3]]]


In [14]:
np.append(a,50)

array([18, 17, 17, 15, 19, 10, 12, 12, 11, 16, 13, 11, 19, 12, 16, 11, 14,
       17, 13, 19, 16, 19, 19, 12, 50])

In [15]:
np.delete(a,(0),axis = 0)

array([[[19, 12, 16, 11],
        [14, 17, 13, 19],
        [16, 19, 19, 12]]])

In [19]:
import numpy as np
a = np.random.randint(2,6,(2,3,3))
print(a)
print(a.shape)

[[[5 5 5]
  [2 4 2]
  [2 3 5]]

 [[3 4 2]
  [2 3 2]
  [3 4 3]]]
(2, 3, 3)


In [20]:
np.append(a,b,axis=1)

array([[[5, 5, 5],
        [2, 4, 2],
        [2, 3, 5],
        [2, 4, 2]],

       [[3, 4, 2],
        [2, 3, 2],
        [3, 4, 3],
        [5, 3, 3]]])

In [21]:
np.delete(a,(0,1),axis = 2)

array([[[5],
        [2],
        [5]],

       [[2],
        [2],
        [3]]])

In [22]:
a

array([[[5, 5, 5],
        [2, 4, 2],
        [2, 3, 5]],

       [[3, 4, 2],
        [2, 3, 2],
        [3, 4, 3]]])

In [24]:
np.delete(a,(0,2),axis = 1)

array([[[2, 4, 2]],

       [[2, 3, 2]]])

In [25]:
np.unique(a,return_counts=True)


(array([2, 3, 4, 5]), array([6, 5, 3, 4]))

In [26]:
np.unique(a)

array([2, 3, 4, 5])

In [27]:
a = np.random.randint(2,20,(2,3,3))
print(a)
print(a.shape)

[[[ 3 18 17]
  [11  7  8]
  [ 3 17  3]]

 [[ 5  2 12]
  [16  7  2]
  [ 9  6  2]]]
(2, 3, 3)


In [28]:

a = [1,2,3]
b= a.copy()
b[0] = 10
print(b)
print(a)

[10, 2, 3]
[1, 2, 3]


In [29]:
a = [1,2,3]
b= a
b[0] = 10
print(b)
print(a)

[10, 2, 3]
[10, 2, 3]


In [30]:
np.unique(a,return_counts=True,return_index=True)


(array([ 2,  3, 10]), array([1, 2, 0]), array([1, 1, 1]))

In [31]:
np.arange(3) + 5

array([5, 6, 7])

In [32]:
a = np.array([2,34,12])
b = a.copy()
b[0] = -999
print(b)
print(a)

[-999   34   12]
[ 2 34 12]


In [33]:
a = np.array([2,34,12])
b = a
b[0] = -999
print(b)
print(a)

[-999   34   12]
[-999   34   12]


In [34]:
np.arange(3).reshape((3,1)) + np.arange(4)


array([[0, 1, 2, 3],
       [1, 2, 3, 4],
       [2, 3, 4, 5]])

In [35]:
np.arange(3).reshape((3,1)) + np.arange(3)


array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

In [36]:
np.ones((3,3)) + np.arange(3)

array([[1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.]])

In [37]:
np.arange(2)

array([0, 1])

In [38]:

a = np.random.randint(2,6,(2,4))
print(a)
b = np.random.randint(0,5,(2,4))
print(b)

[[5 2 5 2]
 [3 5 3 4]]
[[4 4 3 3]
 [1 1 0 3]]


In [39]:
a = np.random.randint(2,6,(2,4))
print(a)
b = np.random.randint(1,10,(2,2))
print(b)

[[2 2 2 2]
 [3 4 5 2]]
[[1 5]
 [2 2]]


In [41]:
a = np.random.randint(2,6,(2,4))
print(a)
b = np.random.randint(1,10,(4,2)) # Changed the shape of 'b' to (4, 2) for matrix multiplication
print(b)
np.matmul(a,b)  # Use np.matmul for matrix multiplication or a @ b

[[5 4 2 4]
 [2 4 4 2]]
[[4 3]
 [8 7]
 [2 5]
 [9 9]]


array([[92, 89],
       [66, 72]])

In [42]:

a=np.random.randint(5,9,(2,4))
print(a)

[[7 5 7 5]
 [5 6 8 6]]


In [43]:
print(np.sum(a))
print(np.sum(a,axis = 0))
print(np.sum(a,axis = 1))

49
[12 11 15 11]
[24 25]


In [44]:
print(np.min(a))
print(np.min(a,axis=1)) #Across Column
a =np.random.randint(0,20,(3,3))
print(a)

5
[5 5]
[[19  8  1]
 [18  5 12]
 [10 12  7]]


In [45]:
print(np.sort(a,axis=0)) # Ascending


[[10  5  1]
 [18  8  7]
 [19 12 12]]


In [46]:
print(np.sort(a,axis=1))

[[ 1  8 19]
 [ 5 12 18]
 [ 7 10 12]]


In [47]:
print(-np.sort(-a,axis=1)) #Descending


[[19  8  1]
 [18 12  5]
 [12 10  7]]


In [48]:
sum(np.arange(3)*np.arange(3).transpose())


5